# Generated by Django 2.1.3 on 2018-12-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='gender',
            field=models.CharField(default=None, max_length=1),
        ),
    ]
