# Generated by Django 2.1.3 on 2019-01-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
