# Generated by Django 2.1.3 on 2019-01-13 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('netsoc', '0002_auto_20190113_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed', to=settings.AUTH_USER_MODEL),
        ),
    ]
