# Generated by Django 2.1.3 on 2019-01-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netsoc', '0004_auto_20190108_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='followers',
        ),
    ]
