# Generated by Django 2.1.3 on 2019-01-08 20:18

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('netsoc', '0005_remove_user_profile_followers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user_profile',
            managers=[
                ('followers', django.db.models.manager.Manager()),
            ],
        ),
    ]
