# Generated by Django 2.1.3 on 2019-01-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netsoc', '0006_auto_20190108_2018'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user_profile',
            managers=[
            ],
        ),
    ]
